filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/kafka_writer/*
  tags: ["kafka_writer"]
  json:
    keys_under_root: true
    add_error_key: true
- type: log
  enabled: true
  paths:
    - /var/log/etl/*
  tags: ["etl"]
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5045"]