version: '2.2'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logstash/logstash.conf:/config/logstash.conf:ro
    networks:
      - movies_network
    command: logstash -f /config/logstash.conf
    environment:
      ES_HOST: "elasticsearch:9200"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    networks:
      - movies_network
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - movies_network
    depends_on:
      - elasticsearch

networks:
  movies_network:
    external: true